org: reflexer
app: incentive-dashboard
service: geb-incentives-dashboard

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    ETH_RPC: ${param:ETH_RPC}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/doc"

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true

plugins:
  - 'serverless-webpack'

functions:   
  get:
    handler: src/handlers.get
    events:
      - http:
          path: /
          method: get
          cors: true
  cron:
    handler: src/handlers.cron
    timeout: 240
    events:
      - schedule: 
          rate: rate(10 minutes)

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: doc
